### ISSUE TITLE
Wrong install command line

### ISSUE THREAD

**Issue by iamalexm** [getgrav/grav-plugin-shortcode-owl-carousel#15]
Hi, 

In the Readme.md in the installation tutorial, you say that the command line to install the plugin is : 

`$ bin/gpm install shortcode-grav-carousel`

but it's not working. The correct line to write is : 

`$ bin/gpm install shortcode-owl-carousel`

Please change the file with the correct command line.

Thanks!

**Comment by rhukster** [comment]
fixed.
