### ISSUE TITLE
Assets are not loaded in modular

### ISSUE THREAD

**Issue by jza34** [getgrav/grav-plugin-shortcode-owl-carousel#16]
Assets are not loaded in modular page... It works in default page only.

**Comment by rhukster** [comment]
Scratch that, can reproduce.. I will look at it..

**Comment by gamahachaa** [comment]
Hi Andy,

PHP 7.3 Grav 1.6.8 owl 1.0.2
owl shortcode inside a modular still doesn't add the assets (works fine on regular pages).

Best

PS : I can share a dump of the site if needed

**Comment by jza34** [comment]
Hi, and thank you because it works for me : assets are now loaded in a modular page
Grav v1.6.9
PHP-FPM v7.3.4
Shortcode Core v4.1.1
Shortcode Owl Carousel v1.0.2
