### ISSUE TITLE
Not working in modular page

### ISSUE THREAD

**Issue by jza34** [getgrav/grav-plugin-shortcode-owl-carousel#17]
Thanks developpers for having fixed assets loading in modular pages  #16 , it works!
But now, in a modular page, the carousel is hidden even if JS and CSS are loaded fine.
The carousel still works fine in regular page.

Grav v1.6.9 
PHP-FPM v7.3.4
Shortcode Core v4.1.1
Shortcode Owl Carousel v1.0.2

**Comment by rhukster** [comment]
Do you have a URL as an example?

**Comment by withindale** [comment]
Similar issue using Supra.

```
[owl-carousel]
![](XLS01.jpg)
![](XLS02.jpg)
[/owl-carousel]
![](XLS01.jpg)
![](XLS02.jpg)
```
displays following, with images below:

```
<img alt="" src="/grav-en/user/pages/02.labelling/11.applicators/08.novexx-xls/XLS01.jpg" /> 
<img alt="" src="/grav-en/user/pages/02.labelling/11.applicators/08.novexx-xls/XLS02.jpg" /> 
<img alt="" src="/grav-en/user/pages/02.labelling/11.applicators/08.novexx-xls/XLS03.jpg" />
```
 URL: https://www.codeway.biz/grav-en/labelling/applicators/novexx-xls

**Comment by jza34** [comment]
Here it is not working (should be displayed at the top, below the menu) in homepage : http://grav-dev.amatiq.fr/www.domainelapeyriere.fr
But works fine (at the bottom of the page above the footer) in a regular page : http://grav-dev.amatiq.fr/www.domainelapeyriere.fr/le-domaine

Same markdown code for both. This website is under a Multisite configuration (directory based not domain based)

**Comment by rhukster** [comment]
I see everything but the inlineJS that is needed to initialize OwlCarousel.  Are you running the latest versions of Grav + Shortcode-Core ???

**Comment by jza34** [comment]
You are right about what is missing, see below the version I use :

Grav v1.6.9
PHP-FPM v7.3.4
Shortcode Core v4.1.1
Shortcode Owl Carousel v1.0.2

**Comment by jza34** [comment]
Sorry I closed the issue by misclicking... so I re-opened it immediately.

**Comment by rhukster** [comment]
I think your problem is related to your theme not having the correct Assets structure in the `<head>`.  Please refer to this: https://getgrav.org/blog/important-theme-updates for the correct structure.

**Comment by jza34** [comment]
Thanks! You are right I have followed the guideline you provided and it works.
Modifying the `<head>` section of my base template, assets are now called with:
```
{% block assets deferred %}
    {{ assets.css()|raw }}
    {{ assets.js()|raw }}
{% endblock %}
```

For me you can close this issue, thank you.

**Comment by withindale** [comment]
Thank you. Will check when back from a trip.

**Comment by Sogl** [comment]
I have right `<head>` structure, but assets not load and carousel doesn't work (
