### ISSUE TITLE
Raw HTML shown instead of an image

### ISSUE THREAD

**Issue by awrog** [getgrav/grav-plugin-shortcode-owl-carousel#18]
Any known issues with Grav v1.6.16 / Quark Open Publishing v1.9.8?
It does not seem to [work](http://kerst035.nl/grav/palace-residence), instead of a carousel it renders:

`<img alt="" src="/grav/images/e/a/b/3/6/eab365a772c7f400ddd759cf68bdc6418a26fc63-3012160.jpeg" /> <img alt="" src="/grav/images/8/c/1/2/3/8c123434fba192787648a2e73a1712279717379b-3072160.jpeg" /> <img alt="" src="/grav/images/8/c/e/b/6/8ceb6e154c349180719f23b30c389b6a1101e122-3262160.jpeg" />`

**Comment by awrog** [comment]
@rhukster The plugin works fine in a fresh Quark install.
It fails in the Open publishing skeleton, even when I select the Quark Theme.

Any suggestions?

**Comment by alucardthefish** [comment]
I have the same issue! It's a long time since you posted this and seems it wasn't fix yet

**Comment by mahagr** [comment]
Repo is here: https://github.com/hibbitts-design/grav-theme-quark-open-publishing

Maybe report the bug into there?

**Comment by alucardthefish** [comment]
> Repo is here: https://github.com/hibbitts-design/grav-theme-quark-open-publishing
> 
> Maybe report the bug into there?

I have tested it on different themes and the problem is still there, so.. maybe not.

**Comment by mahagr** [comment]
Do you mean that you see html code instead of image? Twig must be missing `|raw` filter, then.

**Comment by alucardthefish** [comment]
> Do you mean that you see html code instead of image? Twig must be missing `|raw` filter, then.

Yes, that was the problem.

**Comment by mahagr** [comment]
@rhukster Release needed!
