### ISSUE TITLE
1.7: Template requires |raw filter

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav-plugin-shortcode-owl-carousel#23]
After upgrading to Grav 1.7, the output of the template is escaped and therefor broken.

Solution:
```
{{ owl_items|regex_replace('(^\n?<p>|<\/p>$)','') | raw }}
```

**Comment by 01Kuzma** [comment]
@pamtbaau thank you that you have posted it!
I've spent hours finding out the problem

**Comment by mahagr** [comment]
@pamtbaau Can you create a pull request on this, thanks!

**Comment by pamtbaau** [comment]
Submitted PR per your request: [Template requires filter |raw #25](https://github.com/getgrav/grav-plugin-shortcode-owl-carousel/pull/25)

**Comment by mahagr** [comment]
Thanks, now we need @rhukster to do the release.

**Comment by rhukster** [comment]
released
